name: jg-dealerfinance Auto-Release

on:
  release:
    types: [published]

jobs:
  package:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # 1. Get version from tag
      - name: Extract version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      # 2. Checkout code (include all files)
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 3. Update fxmanifest version automatically
      - name: Update version
        run: |
          sed -i "s/^version .*/version '${{ env.VERSION }}'/" fxmanifest.lua
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add fxmanifest.lua
          git commit -m "Auto-update to ${{ env.VERSION }}" || echo "No version change needed"
          git push || echo "No changes to push"

      # 4. Build UI (if UI folder exists)
      - name: Build UI
        if: exists('ui/package.json')
        run: |
          cd ui
          npm ci
          npm run build
          cd ..

      # 5. Create ZIP with EVERYTHING (except .git and node_modules)
      - name: Package release
        run: |
          # Create clean folder
          mkdir -p jg-dealerfinance-${{ env.VERSION }}
          
          # Copy ALL FILES except ignored ones
          rsync -a --exclude='.git/' --exclude='.github/' --exclude='node_modules/' \
                --exclude='*.zip' ./ jg-dealerfinance-${{ env.VERSION }}/
          
          # Create zip
          zip -r jg-dealerfinance-${{ env.VERSION }}.zip jg-dealerfinance-${{ env.VERSION }}

      # 6. Attach to release
      - name: Upload release
        uses: softprops/action-gh-release@v1
        with:
          files: jg-dealerfinance-${{ env.VERSION }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
