name: jg-dealerfinance Auto-Release

on:
  release:
    types: [published]

jobs:
  package:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # 1. Get version from tag
      - name: Extract version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      # 2. Checkout code
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 3. Update fxmanifest version
      - name: Update version
        run: |
          sed -i "s/^version .*/version '${{ env.VERSION }}'/" fxmanifest.lua
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add fxmanifest.lua
          git commit -m "Auto-update to ${{ env.VERSION }}" || echo "No version change needed"
          git push || echo "No changes to push"

      # 4. Build UI (if exists)
      - name: Build UI
        if: exists('ui/package.json')
        run: |
          cd ui
          npm ci
          npm run build
          cd ..

      # 5. Create ZIP with PERFECT structure
      - name: Create release zip
        run: |
          # Create zip directly with correct internal folder structure
          zip -r jg-dealerfinance-${{ env.VERSION }}.zip \
            -x "*.git*" \
            -x "*.github*" \
            -x "*node_modules*" \
            -x "*.zip" \
            * .[^.]*

      # 6. Upload release
      - name: Upload release
        uses: softprops/action-gh-release@v1
        with:
          files: jg-dealerfinance-${{ env.VERSION }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
