name: jg-dealerfinance Release Automation

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Get tag version
        run: echo "VERSION_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update fxmanifest version
        run: sed -i "s/^version .*/version '${{ env.VERSION_TAG }}'/" fxmanifest.lua

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Build UI
        run: |
          cd ui
          npm ci
          npm run build
          cd ..

      - name: Create complete bundle
        run: |
          # Copy ALL FILES except what's in .gitignore
          mkdir -p ./temp/jg-dealerfinance
          cp -r ./* ./temp/jg-dealerfinance/ || true  # Ignore minor copy errors
          
          # Overwrite with fresh UI build
          rm -rf ./temp/jg-dealerfinance/ui/dist
          cp -r ui/dist ./temp/jg-dealerfinance/ui/
          
          # Create zip (excluding hidden files like .git)
          cd ./temp
          zip -r ../jg-dealerfinance-${{ env.VERSION_TAG }}.zip ./jg-dealerfinance -x "*/.*"
          cd ..

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./jg-dealerfinance-${{ env.VERSION_TAG }}.zip
          asset_name: jg-dealerfinance-${{ env.VERSION_TAG }}.zip
          asset_content_type: application/zip
