name: jg-dealerfinance Auto-Release

on:
  release:
    types: [published]

jobs:
  package:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # 1. Get version from tag
      - name: Extract version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      # 2. Checkout code
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 3. Update fxmanifest version
      - name: Update version
        run: |
          sed -i "s/^version .*/version '${{ env.VERSION }}'/" fxmanifest.lua
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add fxmanifest.lua
          git commit -m "Auto-update to ${{ env.VERSION }}" || echo "No version change needed"
          git push || echo "No changes to push"

      # 4. Check for UI
      - name: Check for UI
        id: check_ui
        run: |
          if [ -f "ui/package.json" ]; then
            echo "UI_EXISTS=true" >> $GITHUB_OUTPUT
          else
            echo "UI_EXISTS=false" >> $GITHUB_OUTPUT
          fi

      # 5. Build UI (if exists)
      - name: Build UI
        if: steps.check_ui.outputs.UI_EXISTS == 'true'
        run: |
          cd ui
          npm ci
          npm run build
          cd ..

      # 6. Create clean package
      - name: Package release
        run: |
          # Create temporary working folder
          mkdir -p package/jg-dealerfinance
          
          # Copy all files except excluded ones
          rsync -a \
            --exclude='.git/' \
            --exclude='.github/' \
            --exclude='node_modules/' \
            --exclude='*.zip' \
            ./ package/jg-dealerfinance/
          
          # Create zip from inside package folder
          cd package
          zip -r ../jg-dealerfinance-${{ env.VERSION }}.zip ./jg-dealerfinance
          cd ..
          
          # Clean up
          rm -rf package

      # 7. Upload release
      - name: Upload release
        uses: softprops/action-gh-release@v1
        with:
          files: jg-dealerfinance-${{ env.VERSION }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
