name: jg-dealerfinance Auto-Release

on:
  release:
    types: [published]

jobs:
  package:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # 1. Get version from tag
      - name: Extract version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      # 2. Checkout code
      - name: Checkout
        uses: actions/checkout@v4

      # 3. Update fxmanifest version
      - name: Update version
        run: |
          sed -i "s/^version .*/version '${{ env.VERSION }}'/" fxmanifest.lua
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add fxmanifest.lua
          git commit -m "Auto-update to ${{ env.VERSION }}" || echo "No version change needed"
          git push || echo "No changes to push"

      # 4. Build UI (only if ui/ exists)
      - name: Build UI
        run: |
          if [ -d "ui" ]; then
            cd ui
            npm ci
            npm run build
            cd ..
          fi

      # 5. Create ZIP - SIMPLE AND CLEAN
      - name: Create release zip
        run: |
          zip -r jg-dealerfinance-${{ env.VERSION }}.zip \
            -x ".git/*" \
            -x ".github/*" \
            -x "node_modules/*" \
            -x "*.zip" \
            *

      # 6. Upload release
      - name: Upload release
        uses: softprops/action-gh-release@v1
        with:
          files: jg-dealerfinance-${{ env.VERSION }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
