name: jg-dealerfinance Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # 1. Get version from tag
      - name: Get version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      # 2. Checkout code
      - name: Checkout
        uses: actions/checkout@v4

      # 3. Update fxmanifest version
      - name: Update version
        run: |
          sed -i "s/^version .*/version '${{ env.VERSION }}'/" fxmanifest.lua
          git add fxmanifest.lua
          git commit -m "Update version to ${{ env.VERSION }}" || true
          git push || true

      # 4. Build UI if UI folder exists
      - name: Build UI
        run: |
          if [ -d "ui" ]; then
            cd ui
            npm ci
            npm run build
            cd ..
          fi

      # 5. Create ZIP - NO EXTRA FOLDERS
      - name: Create ZIP
        run: |
          # List of files to exclude
          EXCLUDE="*.zip .git/* .github/* node_modules/*"
          
          # Create the damn zip
          zip -r jg-dealerfinance-${{ env.VERSION }}.zip * -x "$EXCLUDE"

      # 6. Upload release
      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          files: jg-dealerfinance-${{ env.VERSION }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
